### ISSUE TITLE
Save and remove callbacks must be used?

### ISSUE THREAD

**Issue by dan335** [lykmapipo/kue-unique#2]
What does this mean?

> Note!:To ensure unique jobs, save callback and remove callback must be passed when working with unique job(s)

Does is mean this will not work?

```
queue.create('jobName').unique('1234').save()
```

I have to add save and remove callbacks to every job that is created?  Event if they don't do anything?

**Comment by lykmapipo** [comment]
@dan335 

If you want to maintain unique job(s) must pass a callback. This will ensure a job all changes has been propagated accordingly to redis.

**Comment by dan335** [comment]
Can you show a quick example?  Your example in github doesn't show how to remove the job.

This was how I was removing them.

    queue.on('job complete', Meteor.bindEnvironment(function(id, result){
      kue.Job.get(id, function(err, job){
        if (err) return;
        job.remove(function(err){
          if (err) throw err;
        });
        }
      });
    }));

But I get an error about job # not found.
