### ISSUE TITLE
performance issue

### ISSUE THREAD

**Issue by bymaximus** [lykmapipo/kue-unique#8]
When adding tons of jobs, iterating over all jobs ids creates a high cpu usage and delay process to add job

        //deserialize string to number
        //once fetched from redis
        _.forEach(data, function (value, key) {
          if (!isNaN(value)) {
            data[key] = parseInt(value);
          }
        });

A good way is to not iterate over this since it is not being used when adding a job. Also it should use redis sets for each queue type and not one set to all queue types

**Comment by lykmapipo** [comment]
@bymaximus 

I will appreciate a spec/test that fail for me to improve the algorithm. 

Sure we have to use `specific redis type` that work for the current use case. We will work on that but PR will be appreciated.
